name: CI

on: [push]

jobs:
  check-formatting:
    name: Check Code Formatting
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v1
      - name: Check
        shell: pwsh
        run: .\tools\codeformat.ps1 -Check

  build:
    name: Build
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v1
      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
      - name: Install dependencies
        run: |
          cd vcpkg
          .\vcpkg --triplet x86-windows-static install ms-gsl doctest
      - name: CMake
        run: |
          cd src
          mkdir build
          cd build
          cmake -A Win32 -DVCPKG_TARGET_TRIPLET=x86-windows-static -DCMAKE_TOOLCHAIN_FILE="../../vcpkg/scripts/buildsystems/vcpkg.cmake" -DGEN_FILE_EXPLORER=OFF ..
      - name: Build Debug
        run: |
          cd src/build/x86
          cmake --build . --config Debug
      - name: Run Tests Debug
        run: |
          cd src/build/x86/bin
          .\noire-formats-test
      - name: Build Release
        run: |
          cd src/build/x86
          cmake --build . --config Release
      - name: Run Tests Release
        run: |
          cd src/build/x86/bin
          .\noire-formats-test